// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfwrpvahaxhzvkdjbhps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmd3JwdmFoYXhoenZrZGpiaHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjA2MTQsImV4cCI6MjA2MzEzNjYxNH0.vyRyIdezjUk9fCgWuJWuBknemsxTWKOTZyRGr7t_Xcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);